# Generated by Django 3.2.13 on 2022-04-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='hancy', max_length=200),
            preserve_default=False,
        ),
    ]
