from django.utils.translation import gettext_lazy as _

GENDER_CHOICES = (
    ("M", _("Male")),
    ("F", _("Female")),
    ("O", _("Other")),
)
PROFICIENCY_CHOICES = (
    ("B", _("Begineer")),
    ('I', _('Intermediate')),
    ("A", _("Advance")),
    ('F', _('Fluent')),
)
LEVEL_CHOICES = (
    ('B', _('Beginner')),
    ('A', _('Advanced')),
)
EDUCATION_LEVEL_CHOICES = (
    ('HD', _('High School Diploma')),
    ('CD', _('College Diploma')),
    ('TD', _('Technical Diploma')),
    ('BD', _('Bachelor’s Degree')),
    ('MD', _('Master’s Degree')),
    ('DD', _('Doctorate Degree')),
    ('OD', _('Other')),
)
TOPIK_LEVEL_CHOICES = (
    ('0', _('None')),
    ('1', _('1')),
    ('2', _('2')),
    ('3', _('3')),
    ('4', _('4')),
    ('5', _('5')),
    ('6', _('6')),
)
COUNTRY_CHOICES = (
    ("AF", _("Afghanistan")),
    ("AX", _("Aland Islands")),
    ("AL", _("Albania")),
    ("DZ", _("Algeria")),
    ("AS", _("American Samoa")),
    ("AD", _("Andorra")),
    ("AO", _("Angola")),
    ("AI", _("Anguilla")),
    ("AQ", _("Antarctica")),
    ("AG", _("Antigua And Barbuda")),
    ("AR", _("Argentina")),
    ("AM", _("Armenia")),
    ("AW", _("Aruba")),
    ("AU", _("Australia")),
    ("AT", _("Austria")),
    ("AZ", _("Azerbaijan")),
    ("BS", _("Bahamas")),
    ("BH", _("Bahrain")),
    ("BD", _("Bangladesh")),
    ("BB", _("Barbados")),
    ("BY", _("Belarus")),
    ("BE", _("Belgium")),
    ("BZ", _("Belize")),
    ("BJ", _("Benin")),
    ("BM", _("Bermuda")),
    ("BT", _("Bhutan")),
    ("BO", _("Bolivia")),
    ("BA", _("Bosnia And Herzegovina")),
    ("BW", _("Botswana")),
    ("BV", _("Bouvet Island")),
    ("BR", _("Brazil")),
    ("IO", _("British Indian Ocean Territory")),
    ("BN", _("Brunei Darussalam")),
    ("BG", _("Bulgaria")),
    ("BF", _("Burkina Faso")),
    ("BI", _("Burundi")),
    ("KH", _("Cambodia")),
    ("CM", _("Cameroon")),
    ("CA", _("Canada")),
    ("CV", _("Cape Verde")),
    ("KY", _("Cayman Islands")),
    ("CF", _("Central African Republic")),
    ("TD", _("Chad")),
    ("CL", _("Chile")),
    ("CN", _("China")),
    ("CX", _("Christmas Island")),
    ("CC", _("Cocos (Keeling) Islands")),
    ("CO", _("Colombia")),
    ("KM", _("Comoros")),
    ("CG", _("Congo")),
    ("CD", _("Congo, Democratic Republic")),
    ("CK", _("Cook Islands")),
    ("CR", _("Costa Rica")),
    ("CI", _("Cote D'Ivoire")),
    ("HR", _("Croatia")),
    ("CU", _("Cuba")),
    ("CY", _("Cyprus")),
    ("CZ", _("Czech Republic")),
    ("DK", _("Denmark")),
    ("DJ", _("Djibouti")),
    ("DM", _("Dominica")),
    ("DO", _("Dominican Republic")),
    ("EC", _("Ecuador")),
    ("EG", _("Egypt")),
    ("SV", _("El Salvador")),
    ("GQ", _("Equatorial Guinea")),
    ("ER", _("Eritrea")),
    ("EE", _("Estonia")),
    ("ET", _("Ethiopia")),
    ("FK", _("Falkland Islands (Malvinas)")),
    ("FO", _("Faroe Islands")),
    ("FJ", _("Fiji")),
    ("FI", _("Finland")),
    ("FR", _("France")),
    ("GF", _("French Guiana")),
    ("PF", _("French Polynesia")),
    ("TF", _("French Southern Territories")),
    ("GA", _("Gabon")),
    ("GM", _("Gambia")),
    ("GE", _("Georgia")),
    ("DE", _("Germany")),
    ("GH", _("Ghana")),
    ("GI", _("Gibraltar")),
    ("GR", _("Greece")),
    ("GL", _("Greenland")),
    ("GD", _("Grenada")),
    ("GP", _("Guadeloupe")),
    ("GU", _("Guam")),
    ("GT", _("Guatemala")),
    ("GG", _("Guernsey")),
    ("GN", _("Guinea")),
    ("GW", _("Guinea-Bissau")),
    ("GY", _("Guyana")),
    ("HT", _("Haiti")),
    ("HM", _("Heard Island & Mcdonald Islands")),
    ("VA", _("Holy See (Vatican City State)")),
    ("HN", _("Honduras")),
    ("HK", _("Hong Kong")),
    ("HU", _("Hungary")),
    ("IS", _("Iceland")),
    ("IN", _("India")),
    ("ID", _("Indonesia")),
    ("IR", _("Iran, Islamic Republic Of")),
    ("IQ", _("Iraq")),
    ("IE", _("Ireland")),
    ("IM", _("Isle Of Man")),
    ("IL", _("Israel")),
    ("IT", _("Italy")),
    ("JM", _("Jamaica")),
    ("JP", _("Japan")),
    ("JE", _("Jersey")),
    ("JO", _("Jordan")),
    ("KZ", _("Kazakhstan")),
    ("KE", _("Kenya")),
    ("KI", _("Kiribati")),
    ("KR", _("Korea")),
    ("KP", _("North Korea")),
    ("KW", _("Kuwait")),
    ("KG", _("Kyrgyzstan")),
    ("LA", _("Lao People's Democratic Republic")),
    ("LV", _("Latvia")),
    ("LB", _("Lebanon")),
    ("LS", _("Lesotho")),
    ("LR", _("Liberia")),
    ("LY", _("Libyan Arab Jamahiriya")),
    ("LI", _("Liechtenstein")),
    ("LT", _("Lithuania")),
    ("LU", _("Luxembourg")),
    ("MO", _("Macao")),
    ("MK", _("Macedonia")),
    ("MG", _("Madagascar")),
    ("MW", _("Malawi")),
    ("MY", _("Malaysia")),
    ("MV", _("Maldives")),
    ("ML", _("Mali")),
    ("MT", _("Malta")),
    ("MH", _("Marshall Islands")),
    ("MQ", _("Martinique")),
    ("MR", _("Mauritania")),
    ("MU", _("Mauritius")),
    ("YT", _("Mayotte")),
    ("MX", _("Mexico")),
    ("FM", _("Micronesia, Federated States Of")),
    ("MD", _("Moldova")),
    ("MC", _("Monaco")),
    ("MN", _("Mongolia")),
    ("ME", _("Montenegro")),
    ("MS", _("Montserrat")),
    ("MA", _("Morocco")),
    ("MZ", _("Mozambique")),
    ("MM", _("Myanmar")),
    ("NA", _("Namibia")),
    ("NR", _("Nauru")),
    ("NP", _("Nepal")),
    ("NL", _("Netherlands")),
    ("AN", _("Netherlands Antilles")),
    ("NC", _("New Caledonia")),
    ("NZ", _("New Zealand")),
    ("NI", _("Nicaragua")),
    ("NE", _("Niger")),
    ("NG", _("Nigeria")),
    ("NU", _("Niue")),
    ("NF", _("Norfolk Island")),
    ("MP", _("Northern Mariana Islands")),
    ("NO", _("Norway")),
    ("OM", _("Oman")),
    ("PK", _("Pakistan")),
    ("PW", _("Palau")),
    ("PS", _("Palestinian Territory, Occupied")),
    ("PA", _("Panama")),
    ("PG", _("Papua New Guinea")),
    ("PY", _("Paraguay")),
    ("PE", _("Peru")),
    ("PH", _("Philippines")),
    ("PN", _("Pitcairn")),
    ("PL", _("Poland")),
    ("PT", _("Portugal")),
    ("PR", _("Puerto Rico")),
    ("QA", _("Qatar")),
    ("RE", _("Reunion")),
    ("RO", _("Romania")),
    ("RU", _("Russian Federation")),
    ("RW", _("Rwanda")),
    ("BL", _("Saint Barthelemy")),
    ("SH", _("Saint Helena")),
    ("KN", _("Saint Kitts And Nevis")),
    ("LC", _("Saint Lucia")),
    ("MF", _("Saint Martin")),
    ("PM", _("Saint Pierre And Miquelon")),
    ("VC", _("Saint Vincent And Grenadines")),
    ("WS", _("Samoa")),
    ("SM", _("San Marino")),
    ("ST", _("Sao Tome And Principe")),
    ("SA", _("Saudi Arabia")),
    ("SN", _("Senegal")),
    ("RS", _("Serbia")),
    ("SC", _("Seychelles")),
    ("SL", _("Sierra Leone")),
    ("SG", _("Singapore")),
    ("SK", _("Slovakia")),
    ("SI", _("Slovenia")),
    ("SB", _("Solomon Islands")),
    ("SO", _("Somalia")),
    ("ZA", _("South Africa")),
    ("GS", _("South Georgia And Sandwich Isl.")),
    ("ES", _("Spain")),
    ("LK", _("Sri Lanka")),
    ("SD", _("Sudan")),
    ("SR", _("Suriname")),
    ("SJ", _("Svalbard And Jan Mayen")),
    ("SZ", _("Swaziland")),
    ("SE", _("Sweden")),
    ("CH", _("Switzerland")),
    ("SY", _("Syrian Arab Republic")),
    ("TW", _("Taiwan")),
    ("TJ", _("Tajikistan")),
    ("TZ", _("Tanzania")),
    ("TH", _("Thailand")),
    ("TL", _("Timor-Leste")),
    ("TG", _("Togo")),
    ("TK", _("Tokelau")),
    ("TO", _("Tonga")),
    ("TT", _("Trinidad And Tobago")),
    ("TN", _("Tunisia")),
    ("TR", _("Turkey")),
    ("TM", _("Turkmenistan")),
    ("TC", _("Turks And Caicos Islands")),
    ("TV", _("Tuvalu")),
    ("UG", _("Uganda")),
    ("UA", _("Ukraine")),
    ("AE", _("United Arab Emirates")),
    ("GB", _("United Kingdom")),
    ("US", _("United States")),
    ("UM", _("United States Outlying Islands")),
    ("UY", _("Uruguay")),
    ("UZ", _("Uzbekistan")),
    ("VU", _("Vanuatu")),
    ("VE", _("Venezuela")),
    ("VN", _("Vietnam")),
    ("VG", _("Virgin Islands, British")),
    ("VI", _("Virgin Islands, U.S.")),
    ("WF", _("Wallis And Futuna")),
    ("EH", _("Western Sahara")),
    ("YE", _("Yemen")),
    ("ZM", _("Zambia")),
    ("ZW", _("Zimbabwe")),
)

LANGUAGE_CHOICES = (
    ("aa", _("Afar")),
    ("ab", _("Abkhazian")),
    ("ae", _("Avestan")),
    ("af", _("Afrikaans")),
    ("ak", _("Akan")),
    ("am", _("Amharic")),
    ("an", _("Aragonese")),
    ("ar", _("Arabic")),
    ("as", _("Assamese")),
    ("av", _("Avaric")),
    ("ay", _("Aymara")),
    ("az", _("Azerbaijani")),
    ("ba", _("Bashkir")),
    ("be", _("Belarusian")),
    ("bg", _("Bulgarian")),
    ("bh", _("Bihari languages")),
    ("bi", _("Bislama")),
    ("bm", _("Bambara")),
    ("bn", _("Bengali")),
    ("bo", _("Tibetan")),
    ("br", _("Breton")),
    ("bs", _("Bosnian")),
    ("ca", _("Catalan")),
    ("ce", _("Chechen")),
    ("ch", _("Chamorro")),
    ("co", _("Corsican")),
    ("cr", _("Cree")),
    ("cs", _("Czech")),
    ("cu", _("Church Slavic; Old Slavonic")),
    ("cv", _("Chuvash")),
    ("cy", _("Welsh")),
    ("da", _("Danish")),
    ("de", _("German")),
    ("dv", _("Divehi; Dhivehi; Maldivian")),
    ("dz", _("Dzongkha")),
    ("ee", _("Ewe")),
    ("el", _("Greek")),
    ("en", _("English")),
    ("eo", _("Esperanto")),
    ("es", _("Spanish; Castilian")),
    ("et", _("Estonian")),
    ("eu", _("Basque")),
    ("fa", _("Persian")),
    ("ff", _("Fulah")),
    ("fi", _("Finnish")),
    ("fj", _("Fijian")),
    ("fo", _("Faroese")),
    ("fr", _("French")),
    ("fy", _("Western Frisian")),
    ("ga", _("Irish")),
    ("gd", _("Gaelic; Scottish Gaelic")),
    ("gl", _("Galician")),
    ("gn", _("Guarani")),
    ("gu", _("Gujarati")),
    ("gv", _("Manx")),
    ("ha", _("Hausa")),
    ("he", _("Hebrew")),
    ("hi", _("Hindi")),
    ("ho", _("Hiri Motu")),
    ("hr", _("Croatian")),
    ("ht", _("Haitian; Haitian Creole")),
    ("hu", _("Hungarian")),
    ("hy", _("Armenian")),
    ("hz", _("Herero")),
    ("ia", _("Interlingua")),
    ("id", _("Indonesian")),
    ("ie", _("Interlingue")),
    ("ig", _("Igbo")),
    ("ii", _("Sichuan Yi; Nuosu")),
    ("ik", _("Inupiaq")),
    ("io", _("Ido")),
    ("is", _("Icelandic")),
    ("it", _("Italian")),
    ("iu", _("Inuktitut")),
    ("ja", _("Japanese")),
    ("jv", _("Javanese")),
    ("ka", _("Georgian")),
    ("kg", _("Kongo")),
    ("ki", _("Kikuyu; Gikuyu")),
    ("kj", _("Kwanyama")),
    ("kk", _("Kazakh")),
    ("kl", _("Kalaallisut")),
    ("km", _("Khmer")),
    ("kn", _("Kannada")),
    ("ko", _("Korean")),
    ("kr", _("Kanuri")),
    ("ks", _("Kashmiri")),
    ("ku", _("Kurdish")),
    ("kv", _("Komi")),
    ("kw", _("Cornish")),
    ("ky", _("Kirghiz")),
    ("la", _("Latin")),
    ("lb", _("Luxembourgish")),
    ("lg", _("Ganda")),
    ("li", _("Limburgish")),
    ("ln", _("Lingala")),
    ("lo", _("Lao")),
    ("lt", _("Lithuanian")),
    ("lu", _("Luba-Katanga")),
    ("lv", _("Latvian")),
    ("mg", _("Malagasy")),
    ("mh", _("Marshallese")),
    ("mi", _("Maori")),
    ("mk", _("Macedonian")),
    ("ml", _("Malayalam")),
    ("mn", _("Mongolian")),
    ("mr", _("Marathi")),
    ("ms", _("Malay")),
    ("mt", _("Maltese")),
    ("my", _("Burmese")),
    ("na", _("Nauru")),
    ("nb", _("Norwegian Bokmål")),
    ("nd", _("North Ndebele")),
    ("ne", _("Nepali")),
    ("ng", _("Ndonga")),
    ("nl", _("Dutch")),
    ("nn", _("Norwegian Nynorsk")),
    ("no", _("Norwegian")),
    ("nr", _("South Ndebele")),
    ("nv", _("Navajo; Navaho")),
    ("ny", _("Chichewa; Chewa; Nyanja")),
    ("oc", _("Occitan")),
    ("oj", _("Ojibwa")),
    ("om", _("Oromo")),
    ("or", _("Oriya")),
    ("os", _("Ossetian; Ossetic")),
    ("pa", _("Panjabi; Punjabi")),
    ("pi", _("Pali")),
    ("pl", _("Polish")),
    ("ps", _("Pashto")),
    ("pt", _("Portuguese")),
    ("qu", _("Quechua")),
    ("rm", _("Romansh")),
    ("rn", _("Rundi")),
    ("ro", _("Romanian; Moldavian; Moldovan")),
    ("ru", _("Russian")),
    ("rw", _("Kinyarwanda")),
    ("sa", _("Sanskrit")),
    ("sc", _("Sardinian")),
    ("sd", _("Sindhi")),
    ("se", _("Northern Sami")),
    ("sg", _("Sango")),
    ("si", _("Sinhala; Sinhalese")),
    ("sk", _("Slovak")),
    ("sl", _("Slovenian")),
    ("sm", _("Samoan")),
    ("sn", _("Shona")),
    ("so", _("Somali")),
    ("sq", _("Albanian")),
    ("sr", _("Serbian")),
    ("ss", _("Swati")),
    ("st", _("Southern Sotho")),
    ("su", _("Sundanese")),
    ("sv", _("Swedish")),
    ("sw", _("Swahili")),
    ("ta", _("Tamil")),
    ("te", _("Telugu")),
    ("tg", _("Tajik")),
    ("th", _("Thai")),
    ("ti", _("Tigrinya")),
    ("tk", _("Turkmen")),
    ("tl", _("Tagalog")),
    ("tn", _("Tswana")),
    ("to", _("Tonga")),
    ("tr", _("Turkish")),
    ("ts", _("Tsonga")),
    ("tt", _("Tatar")),
    ("tw", _("Twi")),
    ("ty", _("Tahitian")),
    ("ug", _("Uighur; Uyghur")),
    ("uk", _("Ukrainian")),
    ("ur", _("Urdu")),
    ("uz", _("Uzbek")),
    ("ve", _("Venda")),
    ("vi", _("Vietnamese")),
    ("vo", _("Volapük")),
    ("wa", _("Walloon")),
    ("wo", _("Wolof")),
    ("xh", _("Xhosa")),
    ("yi", _("Yiddish")),
    ("yo", _("Yoruba")),
    ("za", _("Zhuang; Chuang")),
    ("zh", _("Chinese")),
    ("zu", _("Zulu")),
)